config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :materials
  end
  namespace :project do
    resources :materials
  end
  resources :projects do
    resources :tasks
  end
  namespace :project do
    resources :tasks
  end
  devise_for :users
	root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :materials
  has_many :tasks
  belongs_to :user

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
 validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def readable_status
    case status
    when 'not-started'
      'Not started'
    when 'in-progress'
      'In progress'
    when 'complete'
      'Complete'
    end
  end

  def color_class
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end


  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


 def current_user?(user)
     user == current_user
  end

  def after_sign_in_path_for(resource)
     if resource.role == 'admin'
      projects_path
     elsif resource.role == 'staff'
      project_path(@project)
     else
  	  root_path
     end
    end
  helper_method :admin?
    def landlord?
      current_user && current_user.role == "admin"
    end

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :mobile, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:full_name, :mobile, :email, :password, :current_password)}
          end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_project
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET projects/1/materials
  def index
    @materials = @project.materials
  end

  # GET projects/1/materials/1
  def show
  end

  # GET projects/1/materials/new
  def new
    @material = @project.materials.build
  end

  # GET projects/1/materials/1/edit
  def edit
  end

  # POST projects/1/materials
  def create
    @material = @project.materials.build(material_params)

    if @material.save
      redirect_to([@material.project, @material], notice: 'Material was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT projects/1/materials/1
  def update
    if @material.update_attributes(material_params)
      redirect_to([@material.project, @material], notice: 'Material was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/materials/1
  def destroy
    @material.destroy

    redirect_to project_materials_url(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_material
      @material = @project.materials.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def material_params
      params.require(:material).permit(:name, :cost, :total, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id, :total)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)
    @task.user_id = current_user.id if current_user

    if @task.save
      redirect_to([@task.project, @task], notice: 'Task was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to([@task.project, @task], notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to project_tasks_url(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_error.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "App", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%#= link_to "Restaurant", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%#= link_to "Tables",  root_path, class: 'nav-link' %>
      </li>
        <li class="nav-item">
        <%#= link_to "Orders", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%#= link_to "Meals", root_path, class: 'nav-link' %>
      </li>
        <li class="nav-item">
        <%#= link_to "Drinks", root_path, class: 'nav-link' %>
      </li>
   
 
        <% if user_signed_in? %>
          <li><%= link_to 'My Account', edit_user_registration_path, class: "nav-link" %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link" %></li>
        <% else %>
         <li><%= link_to 'Log in', new_user_session_path, class: "nav-link"  %></li>
          <li><%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
        <% end %>
      </div>
  
       </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dyit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/error' %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/materials/_form.html.erb
<%= form_with(model: [@material.project, @material]) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', [@material.project, @material] %> |
<%= link_to 'Back', project_materials_path(@material.project) %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th>Total</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materials.each do |material| %>
  <tr>
    <td><%= material.name %></td>
    <td><%= material.cost %></td>
    <td><%= material.total %></td>
    <td><%= material.project %></td>
    <td><%= link_to 'Show', [material.project, material] %></td>
    <td><%= link_to 'Edit', edit_project_material_path(material.project, material) %></td>
    <td><%= link_to 'Destroy', [material.project, material], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Material', new_project_material_path(params[:project_id]) %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', project_materials_path(@material.project) %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @material.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @material.cost %>
</p>

<p>
  <b>Total:</b>
  <%= @material.total %>
</p>

<p>
  <b>Project:</b>
  <%= @material.project %>
</p>


<%= link_to 'Edit', edit_project_material_path(@material.project, @material) %> |
<%= link_to 'Back', project_materials_path(@material.project) %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="jumbotron shadow-lg p-3 mb-5 rounded">

<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>
    <%= render ProjectOverviewComponent.with_collection(@projects) %>
  </div>
</div>



</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span><%= @project.name %></span>
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-light' %>
        <%= link_to 'Destroy', @project, method: :delete, class: 'btn btn-dark', data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add task</h6>
      <%= form_for([@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4>Tasks</h4>
    <div data-controller="tasks">
      <ul id='tasks-list' data-action="drop->tasks#sort">
        <% @project.tasks.order(position: :desc).each do |task| %>
          <% if task.persisted? %>
            <li class='task-item' data-task-id="<%= task.id %>">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <div class='task-status mb-3'>
                      <i class="fas fa-grip-vertical grip text-secondary mr-1"></i>
                      <%= render(ProgressBadgeComponent.new(status: task.status)) %>
                      <small><%= time_ago_in_words task.created_at %></small>
                    </div>

                    <div>
                      <div class="dropdown float-left">
                        <button class="btn btn-sm mr-1 btn-outline-<%= task.color_class %> dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <%= task.readable_status %>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <% Task::STATUS_OPTIONS.each do |status| %>
                            <a class="dropdown-item" href="#"
                            data-reflex="click->StatusReflex#change"
                            data-id="<%= task.id %>"
                            data-status="<%= status[1] %>">
                              <%= status[0] %>
                            </a>
                          <% end %>
                        </div>
                        <small><%= time_ago_in_words task.updated_at %></small>
                      </div>
                      <%= link_to edit_project_task_path(task.project, task), class: 'btn btn-light btn-sm' do %>
                        <i class='far fa-edit'></i>
                      <% end %>
                      <%= link_to [task.project, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' do %>
                        <i class='fas fa-trash'></i>
                      <% end%>
                    </div>
                  </div>
                  <h5 class='card-title mb-2'>
                    <span><%= task.name %></span>
                  </h5>
                  <p><%= task.description %></p>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.project, @task] %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>